# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"create_tff_client_data_from_df": "00_customclientdata.ipynb"}

modules = ["customclientdata.py",
           "model.py"]

doc_url = "https://City-of-Helsinki.github.io/ml_federated_customer_path/"

git_url = "https://github.com/City-of-Helsinki/ml_federated_customer_path/tree/master/"

def custom_doc_links(name): return None
